services:
  m3:
    container_name: m3
    image: localhost/m3-sim
    environment:
      - GIT_BRANCH=main

      # Info of device run
      - FEATURE_EXTRACTOR=M3SelfAttentionFeatureExtractor
      - COMPUTER_NAME=DuyDT2

      # Tracking
      - TELEGRAM_BOT_TOKEN=7182348523:AAFwetaUraARmTaY2n9vl_R4MJsdBeV8dhw
      - CHAT_ID=-4592566575
      - API_WANDB_TOKEN=hehe

      # Training configs
      - PREFIX_NAME=milestone_mha_penalty_not_both_harder_ta_advice
      - N_SAVED=100
      - KERNEL_SIZE=3
      - MID_CHANNELS=64
      - NUM_FIRST_CNN_LAYER=3
      - NUM_SELF_ATTENTION_LAYERS=8
      - STRATEGY=milestone
      - PI=256
      - VF=256
      - EPOCHS=10
      - ENT_COEF=0.01
      - NUM_HEADS=2
      - N_STEPS=131072
      - OBS_ORDER=none_tile color_1 color_2 color_3 color_4 color_5 pu disco bomb missile_h missile_v plane blocker monster monster_match_dmg_mask monster_match_hp monster_inside_dmg_mask monster_inside_hp self_dmg_mask match_normal match_2x2 match_4_v match_4_h match_L match_T match_5 legal_action heat_mask
      - BATCH_SIZE=1024
      - LEARNING_RATE=0.000012
      - GAMMA=0.8
      - N_UPDATIONS=1
      - NUM_ENVS=8

    volumes:
      - ./_saved_model/:/PPO_M3_Simulator/_saved_model/:rw
